accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import CreateView


app_name = "accounts"
urlpatterns = [
    path("signup/", CreateView.as_view(
        template_name="accounts/signup.html",
        form_class=UserCreationForm,
        success_url='/diary/my_diary',
    ), name="signup"),
    path("login/", LoginView.as_view(
        redirect_authenticated_user=True,
        template_name="accounts/login.html"
    ), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

custoMade/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('diary/', include("diary.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path
from . import views


app_name = "diary"
urlpatterns = [
    path("", views.index, name="index"),
    path("keep_title/", views.keep_title, name="keep_title"),
    path("keep_japanese_translation/", views.keep_japanese_translation, name="keep_japanese_translation"),
    path("keep_own_english_text/", views.keep_own_english_text, name="keep_own_english_text"),
    path("translate_to_english/", views.translate_to_english, name="translate_to_english"),
    path("keep_english_text/", views.keep_english_text, name="keep_english_text"),
    path("my_diary/", views.my_diary, name="my_diary"),
    path("sort_diaries/", views.sort_diaries, name="sort"),
    path("filter_diaries/", views.filter_diaries, name="filter"),
    path("random_diaries/", views.random_diaries, name="random"),
    path('update_check_status/<int:diary_id>/', views.update_check_status, name='update_check_status'),
    path("diary_edit/", views.diary_edit, name="diary_edit"),
]

diary/models.py
from django.db import models
from django.contrib.auth.models import User


class BaseManager(models.Manager):
    def get_or_none(self, **kwargs):
        """
        検索にヒットすればそのモデルを、しなければNoneを返します。
        """
        try:
            return self.get_queryset().get(**kwargs)
        except self.model.DoesNotExist:
            return None


# Create your models here.

# class User(models.Model):
#     nickname = models.CharField(max_length=64, unique=True)
#     password = models.SlugField()
#     diaries = models.PositiveIntegerField(default=0)
#     completed_diaries = models.PositiveIntegerField(default=0)

    # def __str__(self):
    #     return f"\nユーザーID: {self.id}\nニックネーム: {self.nickname}\n日記数: {self.diaries}\n学習済みの日記数: {self.completed_diaries}\n"


class Diary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # date = models.DateField(auto_now_add=True)
    date = models.DateField() #開発環境のみ使用 3/3
    title = models.CharField(max_length=255)
    origin_diary = models.TextField()
    japanese_translation = models.TextField()
    own_english_text = models.TextField()
    english_text = models.TextField()
    image = models.ImageField(upload_to='documents/', blank=True, null=True)
    # completed = models.BooleanField(default=False)
    is_completed = models.CharField(max_length=10, default='unchecked')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "date"],
                name="user_date_unique"
            )
        ]

    objects = BaseManager()

    # def __str__(self):
    #     return f"\n日記ID: {self.id}\nユーザーID: {self.user.id}\n日付: {self.date}\nタイトル: {self.title}\n和文: {self.japanese_translation}\n英文: {self.english_text}\n完了かどうか: {self.completed}\n"


class Count(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    diaries = models.PositiveIntegerField(default=0)
    completed_diaries = models.PositiveIntegerField(default=0)

diary/forms.py
from django import forms
from .models import Diary


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('image',)

diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from datetime import date, datetime
import requests
# import random

# from django.contrib.auth.models import User
from .models import Diary, Count, BaseManager
from .forms import DiaryForm


#################### index.html
# date = date.today()
date = "2021-12-07" #開発環境のみ使用 1/3
diary_step = 1
translate = False


# def index(request):
#     now = datetime.datetime.now()
#     return render(request, "diary/index.html", {
#         "newyear": now.month == 1 and now.day == 1
#     })

# @login_required
# def testview(request):
#     user = request.user


@login_required
def index(request):
    global diary_step
    global translate
    diary = Diary.objects.filter(user=request.user, date=date).first()

    if diary_step > 3 and translate == True:

        # 後ほどユーザーによってAPIキーを分ける処理に変更する
        YOUR_API_KEY = '5ff525e1-0d5f-8846-3081-f374d323b988:fx'

        TEXT = diary.japanese_translation
        params = {
            "auth_key": YOUR_API_KEY,
            "text": TEXT,
            "source_lang": 'JA', # 入力テキストの言語を日本語に設定
            "target_lang": 'EN'  # 出力テキストの言語を英語に設定
        }
        req = requests.post("https://api-free.deepl.com/v2/translate", data=params)
        result = req.json()
        english_text = result["translations"][0]["text"]
        diary.english_text = english_text
        diary.save()

        translate = False

    context = {
        "diary": diary,
        "diary_step": diary_step
    }
    return render(request, "diary/index.html", context)


@login_required
def keep_title(request):
    if (request.method == "POST"):
        global diary_step
        diary_step = 2
        user=request.user

        diary = Diary.objects.get_or_none(user=user, date=date)
        if (not diary == None):
            return redirect('diary:index')

        Diary.objects.create(
            user=user,
            date=date, #開発環境のみ使用 2/3
            title=request.POST.get('title'),
            origin_diary=request.POST.get('origin_diary'),
        )
    return redirect('diary:index')


@login_required
def keep_japanese_translation(request):
    if (request.method == "POST"):
        global diary_step
        diary_step = 3

        Diary.objects.filter(user=request.user, date=date).update(
            title=request.POST.get('title'),
            origin_diary=request.POST.get('origin_diary'),
            japanese_translation=request.POST.get('japanese_translation'),
        )
    return redirect('diary:index')


@login_required
def keep_own_english_text(request):
    if (request.method == "POST"):
        global diary_step
        diary_step = 4

        Diary.objects.filter(user=request.user, date=date).update(
            title=request.POST.get('title'),
            origin_diary=request.POST.get('origin_diary'),
            japanese_translation=request.POST.get('japanese_translation'),
            own_english_text=request.POST.get('own_english_text'),
        )
    return redirect('diary:index')


@login_required
def translate_to_english(request):
    if (request.method == "POST"):
        if 'translate-btn' in request.POST:
            global translate
            translate = True
        else:
            global diary_step
            diary_step = 5

        Diary.objects.filter(user=request.user, date=date).update(
            title=request.POST.get('title'),
            origin_diary=request.POST.get('origin_diary'),
            japanese_translation=request.POST.get('japanese_translation'),
            own_english_text=request.POST.get('own_english_text'),
            english_text=request.POST.get('english_text'),
        )
    return redirect('diary:index')


@login_required
def keep_english_text(request):
    if (request.method == "POST"):
        if 'translate-btn' in request.POST:
            global translate
            translate = True
        else:
            global diary_step
            diary_step = 1

        user=request.user

        diary = Diary.objects.filter(user=user, date=date).first()
        form = DiaryForm(request.POST, request.FILES, instance=diary)
        if form.is_valid():
            form.save()

        Diary.objects.filter(user=user, date=date).update(
            title=request.POST.get('title'),
            origin_diary=request.POST.get('origin_diary'),
            japanese_translation=request.POST.get('japanese_translation'),
            own_english_text=request.POST.get('own_english_text'),
            english_text=request.POST.get('english_text'),
            # image=request.FILES.get('image'),
            # image=request.FILES['image'],
        )

        if not 'translate-btn' in request.POST:
            return redirect('diary:my_diary')
    return redirect('diary:index')
#################### index.html


#################### my_diary.html
sort_state = 0
filter_state = 0
random_state = 0


@login_required
def my_diary(request):
    # print(request.user.id)

    # 新規ユーザーのカウントクエリを自動で生成
    if not Count.objects.filter(user=request.user).exists():
        new = Count(user=request.user)
        new.save()

    global sort_state
    global filter_state
    global random_state
    if random_state == 0:
        if sort_state == 0 and filter_state == 0:
            diaries = Diary.objects.filter(
                user=request.user,
            ).order_by('date').reverse()
        elif sort_state == 0 and filter_state == 1:
            diaries = Diary.objects.filter(
                user=request.user,
                is_completed="unchecked",
            ).order_by('date').reverse()
        elif sort_state == 1 and filter_state == 0:
            diaries = Diary.objects.filter(
                user=request.user,
            ).order_by('date')
        else:
            diaries = Diary.objects.filter(
                user=request.user,
                is_completed="unchecked",
            ).order_by('date')
    else:
        diaries = Diary.objects.filter(
            user=request.user,
            is_completed="unchecked",
        ).order_by('?')[0:3]

    # diaries = Diary.objects.filter(user=request.user)
    count = Count.objects.filter(user=request.user).first()
    count.diaries = Diary.objects.filter(user=request.user).count()
    count.save()

    context = {
        "diaries": diaries,
        "count": count,
        "sort_state": sort_state,
        "filter_state": filter_state,
        "random_state": random_state,
    }
    return render(request, "diary/my_diary.html", context)


@login_required
def sort_diaries(request):
    global sort_state
    if sort_state == 0:
        sort_state = 1
    else:
        sort_state = 0
    return redirect('diary:my_diary')


@login_required
def filter_diaries(request):
    global filter_state
    if filter_state == 0:
        filter_state = 1
    else:
        filter_state = 0
    return redirect('diary:my_diary')


@login_required
def random_diaries(request):
    global random_state
    if random_state == 0:
        random_state = 1
    else:
        random_state = 0
    return redirect('diary:my_diary')


@login_required
def update_check_status(request, diary_id):
    diary = get_object_or_404(Diary, pk=diary_id)
    count = Count.objects.filter(user=request.user).first()
    total = Diary.objects.filter(
            user=request.user,
            is_completed="checked"
            ).count()

    if diary.is_completed == "unchecked":
        diary.is_completed = "checked"
        count.completed_diaries = total+1
    else:
        diary.is_completed = "unchecked"
        count.completed_diaries = total-1
    diary.save()
    count.save()

    return redirect('diary:my_diary')


# 現状いくつかの問題がある(詳細はGoogleDocument)
@login_required
def diary_edit(request):
    if (request.method == "POST"):
        user=request.user
        # target_date=request.POST.get('date')
        target_date=datetime.strptime(request.POST.get('date'), '%b. %d, %Y') #'Dec. 7, 2021'
        diary = Diary.objects.filter(user=user, date=target_date).first()

        if 'update-btn' in request.POST:
            form = DiaryForm(request.POST, request.FILES, instance=diary)
            if form.is_valid():
                form.save()

            Diary.objects.filter(user=user, date=target_date).update(
                title=request.POST.get('title'),
                english_text=request.POST.get('english_text'),
                japanese_translation=request.POST.get('japanese_translation'),
            )
        else:
            diary.delete()
    return redirect('diary:my_diary')
#################### my_diary.html

diary/templates/diary/index.html
{% extends "diary/layout.html" %}

{% block extraheader %}{% endblock %}

{% block main %}
<div class="head-nav">
	<h1>Write a diary!</h1>
</div>

<div class="diary-form">
	{% if diary_step == 1 %}
	<form action="{% url 'diary:keep_title' %}" method="post">
	{% elif diary_step == 2 %}
	<form action="{% url 'diary:keep_japanese_translation' %}" method="post">
	{% elif diary_step == 3 %}
	<form action="{% url 'diary:keep_own_english_text' %}" method="post">
	{% elif diary_step == 4 %}
	<form action="{% url 'diary:translate_to_english' %}" method="post">
	{% else %}
	<form action="{% url 'diary:keep_english_text' %}" method="post" enctype="multipart/form-data">
	{% endif %}

	{% csrf_token %}
		<div class="section">
			<div>
				<label for="title">Title of the diary.</label>
				<input type="text" id="title" name="title" maxlength="64" spellcheck="true" required value="{{diary.title}}">
			</div>

			<div>
				<label for="origin_diary">Write a diary in Japanese.</label>
				<textarea rows="5" id="origin_diary" name="origin_diary" spellcheck="true" required>{{diary.origin_diary}}</textarea>
			</div>

			{% comment %} コメントアウト {% endcomment %}
			{% comment %} <div>
				<label for="image">Add a photo.</label>
				<label class="image-btn">
					select file
					<input type="file" id="image" name="image" accept="image/*" onchange="previewImage(this);">
				</label>
			</div>
			<img id="preview"></img>

			<input type="submit" class="keep-btn" value="Done!"> {% endcomment %}
			{% comment %} コメントアウト {% endcomment %}

			{% if diary_step == 1 %}
			<div class="next-btn">
				<label>
					<input type="submit" value="">
					<i class="fas fa-angle-down fa-3x"></i>
					{% comment %} <i class="fas fa-angle-double-down fa-2x"></i> {% endcomment %}
				</label>
			</div>
			{% endif %}
		</div>
	{% if diary_step == 1 %}
	</form>
	{% endif %}

		{% if diary_step > 1 %}
		<div class="section activate">
		{% else %}
		<div class="section diactivate">
		{% endif %}
			<div class="arrow">
				<i class="fas fa-arrow-down fa-3x"></i>
			</div>

			<div>
				<label for="japanese_translation">Summarize the diary.</label>
				<textarea rows="5" id="japanese_translation" name="japanese_translation" required>{{diary.japanese_translation}}</textarea>
			</div>

			{% if diary_step == 2 %}
			<div class="next-btn">
				<label>
					<input type="submit" value="">
					<i class="fas fa-angle-down fa-3x"></i>
				</label>
			</div>
			{% endif %}
		</div>
	{% if diary_step == 2 %}
	</form>
	{% endif %}

		{% if diary_step > 2 %}
		<div class="section activate">
		{% else %}
		<div class="section diactivate">
		{% endif %}
			<div class="arrow">
				<i class="fas fa-arrow-down fa-3x"></i>
			</div>

			<div>
				<label for="own_english_text">Make it into an English sentence on your own.</label>
				<textarea rows="5" id="own_english_text" name="own_english_text" required>{{diary.own_english_text}}</textarea>
			</div>

			{% if diary_step == 3 %}
			<div class="next-btn">
				<label>
					<input type="submit" value="">
					<i class="fas fa-angle-down fa-3x"></i>
				</label>
			</div>
			{% endif %}
		</div>
	{% if diary_step == 3 %}
	</form>
	{% endif %}

		{% if diary_step > 3 %}
		<div class="section activate">
		{% else %}
		<div class="section diactivate">
		{% endif %}
			<div class="arrow">
				<i class="fas fa-arrow-down fa-3x"></i>
			</div>

			<div>
				<label for="english_text">To translate(example).</label>
				<div class="translate-box">
					<textarea rows="5" id="english_text" name="english_text" readonly>{{diary.english_text}}</textarea>
					<input type="submit" class="translate-btn" name="translate-btn" value="translate">
				</div>
			</div>

			{% if diary_step == 4 %}
			<div class="next-btn">
				<label>
					<input type="submit" value="">
					<i class="fas fa-angle-down fa-3x"></i>
				</label>
			</div>
			{% endif %}
		</div>
	{% if diary_step == 4 %}
	</form>
	{% endif %}

		{% if diary_step > 4 %}
		<div class="section activate">
		{% else %}
		<div class="section diactivate">
		{% endif %}
			<div class="arrow">
				<i class="fas fa-arrow-down fa-3x"></i>
			</div>

			<div>
				<label for="english_text">Compare with and revise your own writing.</label>
				<div class="compare-box">
					<textarea rows="5" readonly>{{diary.own_english_text}}</textarea> {% comment %} placeholder="one’s own writing…" {% endcomment %}
					<textarea rows="5" placeholder="Translated sentence…" id="english_text" name="english_text" required>{{diary.english_text}}</textarea>
				</div>
			</div>

			<div class="select-file-box">
				<label for="image">Add a photo.</label>
				<label class="image-btn">
					select file
					<input type="file" id="image" name="image" accept="image/*" onchange="previewImage(this);">
				</label>
			</div>
			<div class="preview">
				<img id="preview"></img>
			</div>

			<input type="submit" class="keep-btn" value="Done!">
		</div>
	{% if diary_step == 5 %}
	</form>
	{% endif %}
</div>
{% endblock %}

{% block footer %}
	{% if diary_step == 5 %}
	<p class="footer-text"><small>©︎ imkaoru 2021</small></p>
	{% endif %}
{% endblock %}

diary/templates/diary/layout.html
<!DOCTYPE html>
{% load static %}
{% load sass_tags %}

<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>custoMade</title>
        <meta name="description" content="(現在準備中)" />
        <link rel="icon" href="" sizes="16x16" type="image/png" />
        <link rel="apple-touch-icon-precomposed" href="" />
        <link rel='stylesheet' href='https://unpkg.com/ress/dist/ress.min.css'>
        <link rel="stylesheet" href="https://use.typekit.net/kqm8xlk.css">
        <link rel="stylesheet" href="https://use.typekit.net/kqm8xlk.css">
        {% comment %} <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"> {% endcomment %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        {% block extraheader %}{% endblock %}
        {% comment %} <link rel="stylesheet" href="{% static 'diary/styles.css' %}"> {% endcomment %}
        <link rel="stylesheet" href="{% sass_src 'diary/sass/styles.scss' %}">
    </head>

    <body>
        <header>
            <div class="container">
                <nav>
                    {% if user.is_authenticated %} {% comment %} このifいらないかもしれない {% endcomment %}
                    <p class="header-logo">cust<span>M</span>ade</p>

                    <ul class="nav-menu">
                        {% if diary %}
                        <li class="current">
                        {% else %}
                        <li>
                        {% endif %}
                            <a href="{% url 'diary:index' %}">Diary</a>
                        </li>
                        <li>
                            <a href="">(Vocabulary)</a>
                        </li>
                        {% if diaries %}
                        <li class="current">
                        {% else %}
                        <li>
                        {% endif %}
                            <a href="{% url 'diary:my_diary' %}">Pronunciation</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    </ul>
                    {% endif %}
                </nav>
            </div>
        </header>

        <main>
            <div class="container">
                {% block main %}{% endblock %}
            </div>
        </main>

        <footer>
            <div class="container">
                {% block footer %}{% endblock %}
            </div>
        </footer>


        {% comment %} 一旦、jQueryを使用 {% endcomment %}
        <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"
        ></script>
        {% block script %}{% endblock %}
        <script src="{% static 'diary/js/app.js' %}"></script>
    </body>
</html>

diary/templates/diary/my_diary.html
{% extends "diary/layout.html" %}

{% block extraheader %}
<link
    rel="stylesheet"
    type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/Modaal/0.4.4/css/modaal.min.css"
>
{% endblock %}

{% block main %}
<div class="head-nav">
    <h1>Check pronunciation!</h1>

    <div>
        <p>Diary: {{ count.diaries }} &nbsp;&nbsp;&nbsp;Completed: {{ count.completed_diaries }}</p>
        <ul>
            {% if random_state == 0 %}
            <li>
                <a href="{% url 'diary:sort' %}">
                    {% if sort_state == 0 %}
                    <i class="fas fa-sort-amount-up fa-2x diactive"></i>
                    {% comment %} <i class="fas fa-sort-numeric-up-alt fa-2x"></i> {% endcomment %}
                    {% else %}
                    <i class="fas fa-sort-amount-down-alt fa-2x diactive"></i>
                    {% comment %} <i class="fas fa-sort-numeric-down fa-2x"></i> {% endcomment %}
                    {% endif %}
                </a>
            </li>
            <li>
                <a href="{% url 'diary:filter' %}">
                    {% if filter_state == 0 %}
                    <i class="fas fa-filter fa-2x diactive"></i>
                    {% else %}
                    <i class="fas fa-filter fa-2x active"></i>
                    {% endif %}
                </a>
            </li>
            <li class="random-btn">
                <a href="{% url 'diary:random' %}">
                    <i class="fas fa-random fa-2x diactive"></i>
                </a>
            </li>
            {% else %}
            <li class="random-btn">
                <a href="{% url 'diary:random' %}">
                    <i class="fas fa-random fa-2x active"></i>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

<div class="items">
    {% if diaries %}
    {% comment %} 以下for文で回す {% endcomment %}
    {% for diary in diaries %}
        {% if forloop.counter|divisibleby:"3" %}
        <div class="item multiple-of-3">
        {% else %}
        <div class="item">
        {% endif %}
            <div class="card">
                {% if diary.image %}
                <div class="card-image">
                    <img src="{{ diary.image.url }}" alt="日記の写真" class="resize-image">
                </div>
                {% else %}
                <div class="card-image">
                    <img src="../../static/diary/img/default.png" alt="日記の写真" class="resize-image">
                </div>
                {% endif %}

                <div class="card-content">
                    <p class="card-title">{{ diary.title }}</p>
                    <p class="card-date"><small>{{ diary.date }}</small></p>
                    <div class="card-text-box">
                        <p id="card-text{{ forloop.counter }}" class="card-text">{{ diary.english_text }}</p>
                    </div>

                    <div class="function-box">
                        <ul class="left-function">
                            <li>
                                {% comment %} こっからモーダルウィンドーに飛ばしたい、{% url 'pronunciation' diary.id %} みたいな感じか {% endcomment %}
                                <a href="#speechToText{{ forloop.counter }}" class="speechToText">
                                    <i class="fas fa-microphone fa-2x diactive"></i>
                                </a>
                            </li>
                            <li>
                                <button onclick="textToSpeech({{ forloop.counter }});">
                                    {% comment %} 後ほど、押すたびにアイコンを切り替える処理を加える {% endcomment %}
                                    <i class="fas fa-volume-up fa-2x active"></i>
                                    {% comment %} <i class="far fa-stop-circle"></i> {% endcomment %}
                                </button>
                            </li>
                        </ul>

                        <ul class="right-function">
                            <li>
                                <form action="{% url 'diary:update_check_status' diary.id %}" method="post">
                                {% csrf_token %}
                                    <label>
                                        <input type="checkbox"
                                            name="is_completed"
                                            value="{{ diary.is_completed }}"
                                            class="checkbox"
                                            {{ diary.is_completed }}
                                            onClick="this.form.submit();"
                                        >
                                        <i class="far fa-square fa-2x"></i>
                                        <i class="far fa-check-square fa-2x"></i>
                                    </label>
                                    <input type="submit" value="">
                                </form>
                            </li>
                            <li>
                                <a href="#diary-edit{{ forloop.counter }}" class="diary-edit">edit</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <section>
                    <div class="accordion-btn">
                        {% comment %} 最初のみここから画面に表示 {% endcomment %}
                        <i class="fas fa-plus fa-2x active"></i>
                    </div>
                    <div class="accordion-box">
                        <p>{{ diary.japanese_translation }}</p>
                    </div>
                </section>
            </div>
        </div>

        <section id="speechToText{{ forloop.counter }}" class="hide-area">
            <div class="speechToText-modaal">
                <h2 class="modaal-title">Pronunciation practice :)</h2>
                <p class="english-text">{{ diary.english_text }}</p>
                <hr>
                <div class="result-box" id="result-div{{ forloop.counter }}">
                    {% comment %} 最初のみここから画面に表示 {% endcomment %}
                    <p class="standby">Speak into the microphone. (English)</p>
                </div>
                {% comment %} 音の波を表現したいが、後回したいが後回し {% endcomment %}
                <div class="recording-box">
                    <button id="recording-btn{{ forloop.counter }}" class="recording-btn" onclick="speechToText({{ forloop.counter }});">
                        {% comment %} 最初のみここから画面に表示 {% endcomment %}
                        <i class="fas fa-microphone fa-2x active"></i>
                    </button>
                    <p class="btn-notes"><small>Recording start/stop</small></p>
                </div>
            </div>
        </section>

        <section id="diary-edit{{ forloop.counter }}" class="hide-area">
            <div class="diary-edit-modaal">
                <h2 class="modaal-title">Edit or Delete...</h2>
                {% comment %} <p class="english-text">{{ diary.english_text }}</p> {% endcomment %}

                <form action="{% url 'diary:diary_edit' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div>
                        <label for="title{{ forloop.counter }}">title</label>
                        <input type="text" id="title{{ forloop.counter }}" name="title" maxlength="64" spellcheck="true" required value="{{diary.title}}">
                    </div>
                    <div>
                        <label for="english_text{{ forloop.counter }}">english text</label>
                        <textarea rows="3" id="english_text{{ forloop.counter }}" name="english_text" required>{{diary.english_text}}</textarea>
                    </div>
                    <div>
                        <label for="japanese_translation{{ forloop.counter }}">japanese translation</label>
                        <textarea rows="3" id="japanese_translation{{ forloop.counter }}" name="japanese_translation" required>{{diary.japanese_translation}}</textarea>
                    </div>
                    <div class="select-file-box">
                        <label for="image{{ forloop.counter }}">photo</label>
                        <label class="image-btn">
                            select file
                            <input type="file" id="image{{ forloop.counter }}" name="image" accept="image/*" onchange="editPreviewImage(this, {{ forloop.counter }});">
                        </label>
                    </div>
                    <div class="preview">
                        <img id="preview{{ forloop.counter }}"></img>
                    </div>

                    <input type="hidden" name="date" value="{{diary.date}}">

                    <div class="submit-box">
                        <ul>
                            <li>
                                <a href="{% url 'diary:my_diary' %}" class="cancel-btn">cancel</a>
                            </li>
                            <li>
                                <input type="submit" class="update-btn" name="update-btn" value="update">
                            </li>
                        </ul>
                        <input type="submit" class="delete-btn" value="delete">
                    </div>
                </form>
            </div>
        </section>
    {% endfor %}
    {% else %}
    <div class="no-diary">
        <p>All journals are "completed" :)</p>
        <p>(Or there may be no diary yet. <a href="{% url 'diary:index' %}">Do you want to write a diary？</a>)</p>
    </div>
    {% endif %}
</div> {% comment %} items {% endcomment %}
{% endblock %}

{% block footer %}
	{% comment %} {% if diary_step == 5 %} {% endcomment %}
	<p class="footer-text"><small>©︎ imkaoru 2021</small></p>
	{% comment %} {% endif %} {% endcomment %}
{% endblock %}


{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Modaal/0.4.4/js/modaal.min.js"></script>
{% endblock %}